// 错误常量定义
const ERROR_TYPES = {
    NETWORK_ERROR: 'NETWORK_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    CONFLICT: 'CONFLICT',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    SERVER_ERROR: 'SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR'
};

const ERROR_CODES = {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURCE_NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    NETWORK_ERROR: 500,
    TIMEOUT_ERROR: 1001
};

const ERROR_MESSAGES = {
    [ERROR_TYPES.NETWORK_ERROR]: '网络连接失败',
    [ERROR_TYPES.BAD_REQUEST]: '客户端参数错误',
    [ERROR_TYPES.UNAUTHORIZED]: '未授权或登录态失效',
    [ERROR_TYPES.FORBIDDEN]: '权限不足，无法执行该操作',
    [ERROR_TYPES.RESOURCE_NOT_FOUND]: '资源不存在',
    [ERROR_TYPES.CONFLICT]: '业务冲突，请检查操作是否重复',
    [ERROR_TYPES.UNPROCESSABLE_ENTITY]: '业务规则校验失败，请检查业务逻辑',
    [ERROR_TYPES.SERVER_ERROR]: '服务端未知异常，请稍后重试',
    [ERROR_TYPES.SERVICE_UNAVAILABLE]: '服务暂时不可用，请稍后重试',
    [ERROR_TYPES.TIMEOUT_ERROR]: '请求超时，请稍后重试'
};

// 错误码到错误类型的映射
const ERROR_CODE_TO_TYPE = {
    400: ERROR_TYPES.BAD_REQUEST,
    401: ERROR_TYPES.UNAUTHORIZED,
    403: ERROR_TYPES.FORBIDDEN,
    404: ERROR_TYPES.RESOURCE_NOT_FOUND,
    409: ERROR_TYPES.CONFLICT,
    422: ERROR_TYPES.UNPROCESSABLE_ENTITY,
    500: ERROR_TYPES.SERVER_ERROR,
    503: ERROR_TYPES.SERVICE_UNAVAILABLE
};

// 请求超时时间（30秒）
const REQUEST_TIMEOUT = 30000;


export {
    ERROR_TYPES,
    ERROR_CODES,
    ERROR_MESSAGES,
    ERROR_CODE_TO_TYPE,
    REQUEST_TIMEOUT
}